# Generated by Django 5.1 on 2024-09-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.URLField(blank=True, default='https://freesvg.org/img/abstract-user-flat-4.png', max_length=255, null=True),
        ),
    ]
