# Generated by Django 5.1 on 2024-09-20 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider',
            field=models.CharField(default='local', max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='provider_uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
