# Generated by Django 5.1 on 2024-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customuser_provider_customuser_provider_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='provider_state',
            field=models.BooleanField(default=False),
        ),
    ]
