# Generated by Django 4.1.13 on 2024-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_job_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='job',
            name='education_levels',
        ),
        migrations.RemoveField(
            model_name='job',
            name='level',
        ),
        migrations.RemoveField(
            model_name='job',
            name='levels',
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='education_levels',
            field=models.ManyToManyField(to='api.educationllevel'),
        ),
        migrations.AddField(
            model_name='job',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='levels',
            field=models.ManyToManyField(to='api.level'),
        ),
    ]
