# Generated by Django 4.1.13 on 2024-08-21 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_job_education_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='education_level',
        ),
        migrations.RemoveField(
            model_name='job',
            name='level',
        ),
    ]
