# Generated by Django 5.1 on 2024-10-07 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_freelancer_is_technical_freelancer_is_writer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='assignment_type',
            field=models.ManyToManyField(blank=True, to='api.assignmenttype'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='expertise',
            field=models.ManyToManyField(blank=True, to='api.expertise'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='language',
            field=models.ManyToManyField(blank=True, to='api.language'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='service_type',
            field=models.ManyToManyField(blank=True, to='api.servicetype'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='skills',
            field=models.ManyToManyField(blank=True, to='api.skill'),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='subject',
            field=models.ManyToManyField(blank=True, to='api.subject'),
        ),
    ]
