# Generated by Django 5.1 on 2024-09-05 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_job_education_level_remove_job_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
