# Generated by Django 5.1 on 2024-10-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_freelancer_assignment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_technical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='is_writing',
            field=models.BooleanField(default=False),
        ),
    ]
