# Generated by Django 5.1.1 on 2024-09-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customuser_provider_state'),
        ('api', '0006_job_paid'),
    ]

    operations = [
    ]
