from django.urls import path, include
from .Auth.views import (
    client_info,
    freelancer_info,
    logout_view,
    login,
    verify_otp,
    user,
    create_support,
    get_languages,
    get_assignment_type, 
    get_subjects,
    get_styles,
    get_service_types,
    get_levels,
    get_educations,
    generate_test_topic,
    submit_test,
    change_password_view,
    request_password_reset,
    reset_password,
    get_line_spacing,
    create_user,
    check_email,
    linkedin_callback,
    user_info
)
from .Client.views import (
    update_client_profile,
    change_password, 
    post_job, get_skills, 
    get_expertise, 
    get_user_jobs, 
    job_detail,
    proposal_detail,
    update_client_profile_image,
    accept_proposal,
    decline_proposal,
    job_submissions,
    get_revision_submission,
    job_status,
    mark_submission_satisfied,
    request_revision,
    get_amount_per_page,
    search_jobs_by_client,
    get_jobs_completed, 
    get_jobs_pending,
    get_jobs_with_proposals,
    get_job_counts,
    freelancer_list,
    freelancers_by_reviews,
    active_freelancers,
    search_freelancers,
    freelancer_detail,
    freelancers_worked_with_client,
    invite_freelancer,
    get_invited_jobs,
    verify_payment_and_post_job,
    verify_card_payment_and_post_job,
    upload_profile_image
)
from .Freelancer.views import (
    after_register,
    update_verification_credentials,
    get_freelancer_profile,
    update_profile_image,
    update_skills, 
    post_portfolio, 
    list_portfolios,
    list_jobs,
    get_job_details, 
    list_matching_jobs,
    create_proposal,
    list_proposals,
    get_proposal_details,
    update_proposal,
    delete_proposal,
    start_work,
    list_freelancer_tasks,
    list_pending_jobs,
    list_completed_jobs,
    get_job_detail,
    add_education,
    get_education,
    delete_education,
    delete_portfolio,
    decline_job,
    search_jobs,
    submit_job,
    submit_revision,
    get_job_submission,
    revision_reason,
    user_stats,
    freelancer_stats,
    list_invited_jobs,
    accept_invite,
    decline_invite
)

from .Messaging.views import (
    send_message, get_message_list, get_messages_with_user, get_unread_messages_count, get_user_status, check_staff_status, search_messages_or_users
)
from .Reviews.views import (post_review, user_reviews, other_user_reviews)

from .Support.views import (clients, freelancers, suspended_users, verify_credentials, suspend_user, decline_credentials, hired_freelancers, freelancers_search, clients_search, hired_freelancers_search)

from .Notifications.views import (NotificationViewSet, MarkNotificationAsRead, MarkAllNotificationsAsRead)
from .Payment.views import (create_card, create_paypal, create_mpesa, get_cards, get_paypals, get_mpesas, delete_card, delete_paypal, delete_mpesa, get_wallet_balance)

urlpatterns = [  
    path('check-email/', check_email, name='check_email'),
    path('upload-profile-image/', upload_profile_image, name='upload_profile_image'),
    path('auth/linkedin/callback', linkedin_callback, name='linkedin_callback'),
    path('verify-payment-and-post-job/', verify_payment_and_post_job, name='verify_payment_and_post_job'),
    path('create-user/', create_user, name='create_user'), 
    path('card-post-job/', verify_card_payment_and_post_job, name='verify_card_payment_and'),
    path('api/create-card/', create_card, name='create_card'),
    path('api/create-paypal/', create_paypal, name='create_paypal'),
    path('api/create-mpesa/', create_mpesa, name='create_mpesa'),
    path('api/get-cards/', get_cards, name='get_cards'),
    path('search-messages-users/', search_messages_or_users, name='search_messages_users'),
    path('api/get-paypals/', get_paypals, name='get_paypals'),
    path('api/get-mpesas/', get_mpesas, name='get_mpesas'),
    path('api/delete-card/<int:id>/', delete_card, name='delete_card'),
    path('api/delete-paypal/<int:id>/', delete_paypal, name='delete_paypal'),
    path('api/freelancers/', freelancer_list, name='freelancers-list'),
    path('api/delete-mpesa/<int:id>/', delete_mpesa, name='delete_mpesa'),
    path('api/get-wallet-balance/', get_wallet_balance, name='get_wallet_balance'),
    path('api/get-line-spacing/', get_line_spacing, name='get_line_spacing'),
    path('invite/', invite_freelancer, name='invite-freelancer'),
    path('invites/accept/<int:invite_id>/', accept_invite, name='accept-invite'),
    path('invites/decline/<int:invite_id>/', decline_invite, name='decline-invite'),
    path('api/unread-messages-count/', get_unread_messages_count, name='unread_messages_count'),
    path('user-status/<uuid:user_id>/', get_user_status, name='get_user_status'),
    path('staff-status/', check_staff_status, name='check_staff_status'),

    path('freelancers/by-reviews/', freelancers_by_reviews, name='freelancers_by_reviews'),
    path('freelancers/<uuid:pk>/', freelancer_detail, name='freelancer-detail'),
    path('freelancers/active/', active_freelancers, name='active_freelancers'),
    path('freelancers/search/', search_freelancers, name='search_freelancers'),
    path('invited-jobs/', get_invited_jobs, name='get-invited-jobs'),
    path('freelancer-invited-jobs/', list_invited_jobs, name='list-invited-jobs'),
    path('freelancers/worked-with-client/', freelancers_worked_with_client, name='freelancers-worked-with-client'),

    path('notifications/', NotificationViewSet.as_view({'get': 'list', 'post': 'create'}), name='notifications'),
    path('notifications/<int:pk>/mark-as-read/', MarkNotificationAsRead.as_view(), name='mark-notification-as-read'),
    path('notifications/mark-all-as-read/', MarkAllNotificationsAsRead.as_view(), name='mark-all-notifications-as-read'),
    path('change-user-password/', change_password_view, name='change_user_password'),
    path('api/request-password-reset/', request_password_reset, name='request_password_reset'),
    path('api/reset-password/<uidb64>/<token>/', reset_password, name='reset_password'),
    path('register/support/', create_support, name='support-register'),
    path('user/login/', login, name='support-dashboard-login'),
    path('all-clients/', clients, name='all-clients'),
    path('all-freelancers/', freelancers, name='freelancers'), 
    path('all-suspended/', suspended_users, name='suspended-users'),
    path('generate-test-topic/', generate_test_topic, name='generate_test_topic'),
    path('submit-test/', submit_test, name='submit-test'),
    path('all-orders/', hired_freelancers, name='orders'),
    path('search-clients/', clients_search, name='clients-search'),
    path('order-search/', hired_freelancers_search, name='orders-search'),
    path('search-freelancers/', freelancers_search, name='search-freelancers'),
    path('verify-credentials/<uuid:user_id>/', verify_credentials, name='verify_credentials'),
    path('decline-credentials/<uuid:user_id>/', decline_credentials, name='decline_credentials'),
    path('suspend/<uuid:user_id>/', suspend_user, name='suspend_user'),
    path('client-profile/', client_info, name='client-info'),
    path('freelancer-info/', freelancer_info, name='freelancer-info'),
    path('otp-verify/', verify_otp, name='otp-verify'), 
    path('user/', user, name='user'),
    path('user-info/', user_info, name='user-info'),
    path('change-password/', change_password, name='change-password'),
    path('update-client-profile/', update_client_profile, name='update-client-profile'),
    path('update-client-profile-image/', update_client_profile_image, name='update-client-profile-imaage'),
    path('amount/', get_amount_per_page, name='amount'),
    path('post-job/', post_job, name='post-job'),
    path('skills/', get_skills, name='get-skills'),
    path('subjects/', get_subjects, name='get-subjects'),
    path('levels/', get_levels, name='get-levels'),
    path('educations/', get_educations, name='get-educations'),
    path('sercvice-types/', get_service_types, name='get-service-types'),
    path('styles/', get_styles, name='get-styles'),
    path('assignment-type/', get_assignment_type, name='get-assignment-type'),
    path('languages/', get_languages, name='get-languages'),
    path('expertise/', get_expertise, name='get-expertise'),
    path('get-user-jobs/', get_user_jobs, name='get_user_jobs'),
    path('job-detail/<int:job_id>/', job_detail, name='job-detail'),
    path('after_register/', after_register, name='after_register'),
    path('update_verification_credentials/', update_verification_credentials, name='update_verification_credentials'),
    path('freelancer-profile/', get_freelancer_profile, name='freelancer-profile'),
    path('update-profile-image/', update_profile_image, name='update_profile_image'),
    path('profile-update/', update_skills, name='update_skills'),
    path('logout/', logout_view, name='logout'), 
    path('post-portfolio/', post_portfolio, name='post-portfolio'),
    path('portfolios/', list_portfolios, name='list-portfolios'),
    path('delete-portfolio/<str:portfolio_id>/', delete_portfolio, name='delete-portfolio'),
    path('jobs/', list_jobs, name='list-jobs'),
    path('jobs/<int:job_id>/', get_job_details, name='job-details'),
    path('matching-jobs/', list_matching_jobs, name='list_matching_jobs'),
    path('proposals/create/', create_proposal, name='create_proposal'),
    path('proposals/', list_proposals, name='list_proposals'),
    path('proposals/<int:proposal_id>/', get_proposal_details, name='get_proposal_details'),
    path('proposals/<int:proposal_id>/update/', update_proposal, name='update_proposal'),
    path('proposals/<int:proposal_id>/delete/', delete_proposal, name='delete_proposal'),
    path('proposal-detail/<int:proposal_id>/', proposal_detail, name='proposal_detail'),
    path('proposal/<int:proposal_id>/accept/', accept_proposal, name='accept_proposal'),
    path('proposal/<int:proposal_id>/decline/', decline_proposal, name='decline_proposal'),
    path('start_work/', start_work, name='start_work'),
    path('list-freelancer-tasks/', list_freelancer_tasks, name='list_freelancer_jobs'),
    path('pending-jobs/', list_pending_jobs, name='pending-jobs'),
    path('completed-jobs/', list_completed_jobs, name='completed-jobs'),
    path('task-detail/<int:job_id>/', get_job_detail, name='job-detail'),
    path('send-message/', send_message, name='send-message'),
    path('get-message-list/', get_message_list, name='get-message-list'),
    path('get-messages-with-user/<uuid:user_id>/', get_messages_with_user, name='get-messages-with-user'),

    path('add-education/', add_education, name='add-education'),
    path('get-education/', get_education, name='get-education'),
    path('delete-education/<int:education_id>/', delete_education, name='delete_education'),
    path('decline-job/', decline_job, name='decline_job'),
    path('jobs/search/', search_jobs, name='job-search'),
    path('jobs/submit/<int:job_id>/', submit_job, name='submit-job'),
    path('get-job-submission/<int:job_id>/', get_job_submission, name='get-job-submission'),
    path('revisions/submit/<int:job_id>/', submit_revision, name='submit-revision'),
    path('user/stats/', user_stats, name='user_stats'),
    path('user/stats/<uuid:freelancer_id>/', freelancer_stats, name='freelancer_stats'),

    path('job-submissions/<int:job_id>/', job_submissions, name='job-submissions'),
    path('job-revisions/<int:job_id>/', get_revision_submission, name='job-revisions'),
    path('job-status/<int:job_id>/', job_status, name='job-status'),
    path('mark-submission-satisfied/<int:job_id>/', mark_submission_satisfied, name='mark-submission-satisfied'),
    path('request-revision/<int:job_id>/', request_revision, name='request-revision'),
    path('revision-reason/<int:job_id>/', revision_reason, name='revision-reason'),
    path('post-review/', post_review, name='post_review'),
    path('my-reviews/', user_reviews, name='my-reviews'),
    path('search-client-jobs/', search_jobs_by_client, name="serach-client-jobs"),
    path('other-user-reviews/<uuid:recipient_id>/', other_user_reviews, name='other-user-reviews'),
    path('jobs/completed/', get_jobs_completed, name='get_jobs_completed'),
    path('jobs/pending/', get_jobs_pending, name='get_jobs_pending'),
    path('jobs/count/', get_job_counts, name='get_jobs_pending'),
    path('jobs/proposals/', get_jobs_with_proposals, name='get_with_proposals'),
    
] 
 